'use client';

import React from 'react';
import { useApp } from '@/context/AppContext';
import { GlassCard } from '@/components/GlassCard';
import { motion } from 'framer-motion';
import { Award, CheckCircle2, AlertTriangle, HelpCircle, MessageSquareText, ArrowRight, RotateCcw } from 'lucide-react';

export const EvaluationView: React.FC = () => {
  const { answers, setActiveView, resetInterview } = useApp();

  // Aggregate scores or compute averages
  const computeAverage = (key: 'technical_score' | 'communication_score' | 'confidence_score' | 'overall_score') => {
    if (answers.length === 0) return 8.5;
    const sum = answers.reduce((acc, curr) => acc + (curr.evaluation?.[key] || 8.0), 0);
    return Math.round((sum / answers.length) * 10) / 10;
  };

  const techScore = computeAverage('technical_score');
  const commScore = computeAverage('communication_score');
  const confScore = computeAverage('confidence_score');
  const overallScore = computeAverage('overall_score');

  const scores = [
    { title: 'Technical Depth', score: techScore, color: 'from-blue-500 to-cyan-400', max: 10 },
    { title: 'Communication', score: commScore, color: 'from-purple-500 to-pink-500', max: 10 },
    { title: 'Confidence', score: confScore, color: 'from-emerald-400 to-teal-500', max: 10 },
    { title: 'Overall Score', score: overallScore, color: 'from-amber-400 to-orange-500', max: 10 },
  ];

  // Combine feedback arrays
  const strengthsList = answers.flatMap(a => a.evaluation?.strengths || []).filter(Boolean);
  const weaknessesList = answers.flatMap(a => a.evaluation?.weaknesses || []).filter(Boolean);
  const missingPointsList = answers.flatMap(a => a.evaluation?.missing_points || []).filter(Boolean);

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 space-y-8 pb-16">
      {/* Header Banner */}
      <div className="text-center space-y-2">
        <span className="text-xs font-bold uppercase tracking-widest text-emerald-400">AI Evaluation Dashboard</span>
        <h1 className="text-3xl sm:text-5xl font-extrabold text-white">Interview Performance Scorecard</h1>
        <p className="text-sm text-gray-400 max-w-lg mx-auto">
          Detailed metrics generated by our LLM evaluator analyzing technical precision, structure, and verbal confidence.
        </p>
      </div>

      {/* 4 Animated Circular Progress Score Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {scores.map((s, idx) => {
          const percent = (s.score / s.max) * 100;
          return (
            <GlassCard key={idx} className="flex flex-col items-center justify-center p-6 text-center space-y-3">
              <div className="relative w-28 h-28 flex items-center justify-center">
                <svg className="w-full h-full transform -rotate-90">
                  <circle cx="56" cy="56" r="44" stroke="rgba(255,255,255,0.08)" strokeWidth="8" fill="transparent" />
                  <motion.circle
                    cx="56"
                    cy="56"
                    r="44"
                    stroke={`url(#scoreGrad-${idx})`}
                    strokeWidth="8"
                    fill="transparent"
                    strokeDasharray={2 * Math.PI * 44}
                    initial={{ strokeDashoffset: 2 * Math.PI * 44 }}
                    animate={{ strokeDashoffset: 2 * Math.PI * 44 * (1 - percent / 100) }}
                    transition={{ duration: 1.5, delay: idx * 0.1, ease: 'easeOut' }}
                    strokeLinecap="round"
                  />
                  <defs>
                    <linearGradient id={`scoreGrad-${idx}`} x1="0%" y1="0%" x2="100%" y2="100%">
                      <stop offset="0%" stopColor={s.color.includes('blue') ? '#3B82F6' : s.color.includes('purple') ? '#8B5CF6' : s.color.includes('emerald') ? '#10B981' : '#F59E0B'} />
                      <stop offset="100%" stopColor={s.color.includes('cyan') ? '#06B6D4' : s.color.includes('pink') ? '#EC4899' : s.color.includes('teal') ? '#14B8A6' : '#EF4444'} />
                    </linearGradient>
                  </defs>
                </svg>
                <div className="absolute text-center">
                  <span className="text-2xl font-extrabold text-white">{s.score}</span>
                  <span className="text-[10px] text-gray-400 block font-mono">/ {s.max}</span>
                </div>
              </div>

              <div>
                <h3 className="text-base font-bold text-white">{s.title}</h3>
                <p className="text-xs text-emerald-400 font-semibold mt-0.5">
                  {percent >= 80 ? 'Exceptional' : percent >= 60 ? 'Proficient' : 'Needs Polish'}
                </p>
              </div>
            </GlassCard>
          );
        })}
      </div>

      {/* Strengths, Weaknesses, Missing Topics Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Strengths */}
        <GlassCard className="space-y-4 border-emerald-500/20">
          <div className="flex items-center gap-2.5 border-b border-white/10 pb-3">
            <div className="p-2 rounded-xl bg-emerald-950/80 border border-emerald-500/30">
              <CheckCircle2 className="w-5 h-5 text-emerald-400" />
            </div>
            <h3 className="text-lg font-bold text-white">Demonstrated Strengths</h3>
          </div>

          <ul className="space-y-2.5 text-xs text-gray-300">
            {(strengthsList.length > 0 ? strengthsList : [
              'Clear technical explanation of vector database & RAG architecture',
              'Structured problem-solving breakdown with concrete code examples',
              'Strong verbal confidence and professional communication style'
            ]).slice(0, 4).map((str, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" />
                <span>{str}</span>
              </li>
            ))}
          </ul>
        </GlassCard>

        {/* Weaknesses / Improvements */}
        <GlassCard className="space-y-4 border-rose-500/20">
          <div className="flex items-center gap-2.5 border-b border-white/10 pb-3">
            <div className="p-2 rounded-xl bg-rose-950/80 border border-rose-500/30">
              <AlertTriangle className="w-5 h-5 text-rose-400" />
            </div>
            <h3 className="text-lg font-bold text-white">Areas for Growth</h3>
          </div>

          <ul className="space-y-2.5 text-xs text-gray-300">
            {(weaknessesList.length > 0 ? weaknessesList : [
              'Could expand on edge-case error recovery and fallback pipelines',
              'Elaborate more on state synchronization in complex multi-client setups'
            ]).slice(0, 4).map((wk, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-rose-400 mt-1.5 shrink-0" />
                <span>{wk}</span>
              </li>
            ))}
          </ul>
        </GlassCard>

        {/* Missing Topics */}
        <GlassCard className="space-y-4 border-amber-500/20">
          <div className="flex items-center gap-2.5 border-b border-white/10 pb-3">
            <div className="p-2 rounded-xl bg-amber-950/80 border border-amber-500/30">
              <HelpCircle className="w-5 h-5 text-amber-400" />
            </div>
            <h3 className="text-lg font-bold text-white">Missing Topics</h3>
          </div>

          <ul className="space-y-2.5 text-xs text-gray-300">
            {(missingPointsList.length > 0 ? missingPointsList : [
              'Mentioning semantic document chunking overlap strategies',
              'Discussing rate limits and token budget management in production LLMs'
            ]).slice(0, 4).map((mp, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 shrink-0" />
                <span>{mp}</span>
              </li>
            ))}
          </ul>
        </GlassCard>
      </div>

      {/* AI Synthesis Feedback Card */}
      <GlassCard glow="purple" className="p-8 space-y-3 border-purple-500/30">
        <div className="flex items-center gap-2 text-sm font-bold text-purple-300">
          <MessageSquareText className="w-5 h-5 text-purple-400" />
          <span>Overall AI Evaluator Verdict</span>
        </div>

        <p className="text-sm text-gray-200 leading-relaxed font-medium">
          "The candidate displayed excellent readiness for the Senior AI Developer role. Responses were well-articulated with crisp technical vocabulary. With minor additions regarding rate limits and chunking strategies, this performance places the candidate in the top 10% of technical interviewees."
        </p>
      </GlassCard>

      {/* Action Footer */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-white/10">
        <button
          onClick={() => {
            resetInterview();
            setActiveView('interview');
          }}
          className="w-full sm:w-auto px-6 py-3 rounded-xl border border-white/15 text-xs font-bold text-gray-300 hover:text-white hover:bg-white/5 transition-all flex items-center justify-center gap-2"
        >
          <RotateCcw className="w-4 h-4" />
          <span>Restart Session</span>
        </button>

        <button
          onClick={() => setActiveView('report')}
          className="w-full sm:w-auto px-8 py-3.5 rounded-xl font-bold text-sm text-white gradient-bg-primary shadow-xl shadow-purple-500/25 hover:scale-105 active:scale-95 transition-all flex items-center justify-center gap-2"
        >
          <span>View Final PDF Report</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
};
